#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/crm
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crm
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.multiTenancy: DISCRIMINATOR  # TEMP: we override this later to use DISCRIMINATOR programmatically

logging:
  level:
    org.springframework.security: DEBUG
